# Generated by Django 6.0.6 on 2026-08-25 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Motivo del reporte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del reporte')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='¿Resuelto?')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review', verbose_name='Reseña Reportada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reporta')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
